#!/bin/bash
mkdir -p ~/bin
cd ~/longrun
ln -s ../longrun/bin/longrun.state ~/bin/longrun.state
ln -s ../longrun/bin/launcher ~/bin/launcher
ln -s ../longrun/bin/longrun.start ~/bin/longrun.start
ln -s ../longrun/longrun.js ~/http

